export const THEME_KEY = Symbol('theme')
export const OPTIONS_KEY = Symbol('options')
export const ALERT_KEY = Symbol('alert')
export const AVATAR_KEY = Symbol('avatar')
export const BADGE_KEY = Symbol('badge')
export const TABS_KEY = Symbol('tabs')
